# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM python:3.10-slim

# set working directory
WORKDIR /app

# copy requirements and source code
COPY pyproject.toml requirements.txt ./
COPY README.md medrxiv_server.py medrxiv_web_search.py ./

# install dependencies
RUN pip install --no-cache-dir -r requirements.txt

# expose port if needed (not sure, MCP servers typically run on stdio, so not needed)

# run the server
CMD ["python", "medrxiv_server.py"]
