[project]
name = "mcp-server-medRxiv"
version = "0.1.0"
description = "An MCP server for searching and retrieving articles from medRxiv"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "mcp[cli]>=1.4.1",
    "requests>=2.25.1",
    "beautifulsoup4>=4.9.3",
]
